apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000  # Container port
      nodePort: 31310 
  type: NodePort  # Exposes service externally on a random high port
